// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZA6jH1qWPgXwQuha-Y4etdlhvHEjpcIo',
    appId: '1:939730294445:web:136f6a9c0fe3125d315824',
    messagingSenderId: '939730294445',
    projectId: 'driver-hire-1108a',
    authDomain: 'driver-hire-1108a.firebaseapp.com',
    storageBucket: 'driver-hire-1108a.firebasestorage.app',
    measurementId: 'G-3Y6B8X1MEF',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8sg75dHKDOJo6XfXUU6czTCeepCd13o8',
    appId: '1:939730294445:ios:9eb1ae0baa079c32315824',
    messagingSenderId: '939730294445',
    projectId: 'driver-hire-1108a',
    storageBucket: 'driver-hire-1108a.firebasestorage.app',
    iosBundleId: 'com.example.driverHire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8sg75dHKDOJo6XfXUU6czTCeepCd13o8',
    appId: '1:939730294445:ios:9eb1ae0baa079c32315824',
    messagingSenderId: '939730294445',
    projectId: 'driver-hire-1108a',
    storageBucket: 'driver-hire-1108a.firebasestorage.app',
    iosBundleId: 'com.example.driverHire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZA6jH1qWPgXwQuha-Y4etdlhvHEjpcIo',
    appId: '1:939730294445:web:d8e31ada2fe7273c315824',
    messagingSenderId: '939730294445',
    projectId: 'driver-hire-1108a',
    authDomain: 'driver-hire-1108a.firebaseapp.com',
    storageBucket: 'driver-hire-1108a.firebasestorage.app',
    measurementId: 'G-J4Y5QJB3G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAk2vcXWNW_yIno8Hs0Nvkd9qpnrWshWo',
    appId: '1:939730294445:android:c790ba82236bf239315824',
    messagingSenderId: '939730294445',
    projectId: 'driver-hire-1108a',
    storageBucket: 'driver-hire-1108a.firebasestorage.app',
  );

}